version: 0.2

phases:
  install:
    commands:
      - n 16.5.0

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd my-app
      - npm ci
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - 
artifacts:
  files:
    - '**/*'
  base-directory: build